# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

workflowSchedule:
  graphs: "0 0 * * *"
  uptime: "*/30 * * * *"

sites:
  - name: city-ol.ch
    url: htts://city-ol.ch/
  - name: cityol.ch
    url: https://cityol.ch
  - name: city-ol-brugg.com
    url: https://city-ol-brugg.com
  - name: app.city-ol.ch
    url: https://app.city-ol.ch

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.city-ol.ch
  # baseUrl: /your-repo-name
  logoUrl: https://city-ol.ch/logo.svg
  name: City-OL Status

assignees:
  - timmedia
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
