# Change these first
owner: City-OL # Your GitHub organization or username, where this repository lives
repo: upptime-status # The name of this repository

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/30 * * * *"

sites:
  - name: Web App (app.city-ol.ch)
    url: https://app.city-ol.ch
    slug: webapp
  - name: Backend
    url: $CITY_OL_BACKEND_URL
    icon: https://status.city-ol.ch/favicon.png
    slug: backend
  - name: Tile Server
    url: $CITY_OL_TILE_SERVER_URL
    icon: https://status.city-ol.ch/favicon.png
    slug: tile-server
  - name: Website (city-ol.ch)
    url: https://city-ol.ch/
    slug: website
  - name: Website Alias (cityol.ch)
    url: https://cityol.ch
    slug: website-alias-cityol
  - name: Website Alias (city-ol-brugg.com)
    url: https://city-ol-brugg.com
    slug: website-alias-cityolbrugg

status-website:
  name: City-OL Status
  cname: status.city-ol.ch
  logoUrl: https://status.city-ol.ch/logo.svg
  favicon: https://status.city-ol.ch/favicon.png
  themeUrl: https://status.city-ol.ch/theme.css
  links:
    - rel: stylesheet
      href: https://status.city-ol.ch/styles.css

assignees:
  - timmedia
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
