# Change these first
owner: City-OL # Your GitHub organization or username, where this repository lives
repo: upptime-status # The name of this repository

sites:
  - name: city-ol.ch
    url: https://city-ol.ch/
  - name: cityol.ch
    url: https://cityol.ch
  - name: city-ol-brugg.com
    url: https://city-ol-brugg.com
  - name: app.city-ol.ch
    url: https://app.city-ol.ch

status-website:
  name: City-OL Status
  cname: status.city-ol.ch
  logoUrl: https://status.city-ol.ch/logo.svg
  favicon: https://status.city-ol.ch/favicon.png
  themeUrl: https://status.city-ol.ch/theme.css
  links:
    - rel: stylesheet
      href: https://status.city-ol.ch/styles.css

assignees:
  - timmedia
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
